record LoginRequest(string Email,string Password);
record CreateCompanyRequest(string Name,string AdminName,string AdminEmail,string AdminPassword);
record CompanyStatusRequest(string Status);
record UpdateCompanyRequest(string Name,string? LegalName,string? TaxId,string? Phone,string? Email,string? Address,string? LogoDataUrl,int ExceptionalMileageThreshold);
record NotificationSettingsRequest(bool Enabled,bool Internal,bool EmailEnabled,string? Email,bool DueSoon,bool Overdue,int RepeatDays);
record MarkNotificationRequest(Guid VehicleId,Guid ServiceId,string Status,string? Channel,string? Recipient);
record CreateUserRequest(string FullName,string Email,string Password,string Role);
record TechnicianSelectVehicleRequest(Guid? VehicleId,string? QrToken);
record UserStatusRequest(string Status);
record UpdateUserRequest(string FullName,string Email,string Role);
record ResetUserPasswordRequest(string Password);
record ChangeOwnPasswordRequest(string CurrentPassword,string NewPassword);
record CreateVehicleRequest(string Plate,string? InternalNumber,string Brand,string Model,string? Variant,int CurrentMileage,Guid? PlanVersionId);
record UpdateVehicleRequest(string Plate,string? InternalNumber,string Brand,string Model,Guid PlanVersionId);
record ReactivateVehicleRequest(Guid PlanVersionId);
record MileageRequest(int Mileage,bool ExceptionConfirmed=false);
record HistoricalMileageRequest(int Mileage,DateTime ReadingDate);
record CorrectMileageRequest(int Mileage);
record DemoUser(Guid Id,Guid CompanyId,string FullName,string Email,string PasswordHash,string Role);
record CreatePlanRequest(string Name,string Brand,string Model,string? Variant);
record UpdatePlanRequest(string Name,string Brand,string Model);
record CreateServiceRequest(string Name,string Category,string? Specification,int? IntervalKm,int? IntervalMonths,int? PrealertKm,int? PrealertDays);
record UpdateServiceRequest(string Name,string? Specification,int? IntervalKm,int? IntervalMonths,int? PrealertKm,int? PrealertDays);
record AssignPlanRequest(Guid PlanVersionId);
record BaselineRequest(Guid PlanServiceId,int? LastServiceMileage,DateTime? LastServiceDate);
record RegisterMaintenanceRequest(int Mileage,DateTime ServiceDate,List<Guid> ServiceIds,string? Notes,bool ExceptionConfirmed=false);
record MaintenanceStatusItem(Guid ServiceId,string Name,string Status,int? NextDueMileage,DateTime? NextDueDate,int? RemainingKm,int? RemainingDays);

record DashboardVehicle(Guid Id,string Plate,string? InternalNumber,string Brand,string Model,string? Variant,int CurrentMileage,List<MaintenanceStatusItem> Services);
record DashboardPriority(Guid VehicleId,string Plate,string? InternalNumber,string Brand,string Model,string? Variant,int CurrentMileage,Guid ServiceId,string ServiceName,string Status,int? NextDueMileage,int? RemainingKm,DateTime? NextDueDate,double? AverageKmPerDay,int? EstimatedDays,DateTime? EstimatedDate,int PredictionSampleDays);
record VehiclePrediction(double AverageKmPerDay,int SampleDays,double Variability,string Confidence);
