async function renderDashboard(vehicles=[]){
 const main=document.getElementById('main');main.innerHTML=card('<h1>Centro de Control</h1><p class="muted">Cargando estado de la flota…</p>');
 const out=await req(api+'/dashboard');if(!out.r||!out.r.ok){main.innerHTML=card('<h1>Centro de Control</h1><p class="error">No se pudo cargar el tablero.</p>');return}
 const d=out.j.data,rows=d.priorities||[],updates=d.todayUpdates||[];
 const staleMileage=(vehicles||[]).filter(v=>{const t=new Date(v.mileageUpdatedAt).getTime();return Number.isFinite(t)&&Date.now()-t>24*60*60*1000}).sort((x,y)=>new Date(x.mileageUpdatedAt)-new Date(y.mileageUpdatedAt));
 const serviceCounts={UP_TO_DATE:0,DUE_SOON:0,OVERDUE:0,NO_BASELINE:0};rows.forEach(x=>{if(serviceCounts[x.status]!=null)serviceCounts[x.status]++});
 const totalServices=Object.values(serviceCounts).reduce((x,y)=>x+y,0)||1;
 const pct=s=>Math.round((serviceCounts[s]||0)*100/totalServices);
 const common=[...rows.reduce((m,x)=>(m.set(x.serviceName,(m.get(x.serviceName)||0)+1),m),new Map()).entries()].sort((x,y)=>y[1]-x[1]).slice(0,5);
 const urgent=rows.filter(x=>x.status==='OVERDUE'||x.status==='DUE_SOON').slice(0,5);
 const sourceLabel=x=>x==='PUBLIC_QR'?'Conductor':x==='TECHNICIAN'?'Técnico':x==='MAINTENANCE'?'Técnico':'Sistema';
 main.innerHTML=`<div class="cc-head"><div><h1>Centro de Control</h1><p>Resumen general de la flota</p></div><button id="refreshdash" class="secondary">Actualizar</button></div>
 <section class="cc-kpis">
  <article class="cc-kpi blue"><div class="cc-kpi-icon">${uiIcon('vehicle')}</div><div><small>Vehículos activos</small><strong>${d.total}</strong><span>Total en flota</span></div></article>
  <article class="cc-kpi orange clickable" data-status="DUE_SOON"><div class="cc-kpi-icon">${uiIcon('service')}</div><div><small>Próximos servicios</small><strong>${d.dueSoon}</strong><span>Vehículos próximos</span></div></article>
  <article class="cc-kpi red clickable" data-status="OVERDUE"><div class="cc-kpi-icon">${uiIcon('alert')}</div><div><small>En alerta</small><strong>${d.overdue}</strong><span>Vehículos vencidos</span></div></article>
  <article class="cc-kpi slate clickable" id="staleMileageCard"><div class="cc-kpi-icon">${uiIcon('gauge')}</div><div><small>Sin kilometraje hoy</small><strong>${staleMileage.length}</strong><span>Más de 1 día sin actualizar</span></div></article>
 </section>
 <section class="cc-grid">
  <article class="cc-panel"><div class="cc-panel-head"><h2>Próximos servicios</h2><button class="textbtn" id="showAllDue">Ver todos</button></div><div class="cc-list">${urgent.length?urgent.map(x=>`<button class="cc-service-row dashmaint" data-vehicle="${x.vehicleId}"><span class="cc-service-icon">${serviceIcon(x.serviceName)}</span><span class="cc-service-main"><small>${x.internalNumber?`Interno ${esc(x.internalNumber)}`:''}</small><b>${esc(x.plate)}</b><em>${esc(x.serviceName)}</em></span><span class="cc-service-due ${x.status==='OVERDUE'?'badtext':''}">${x.remainingKm==null?'—':x.remainingKm<0?`Vencido ${fmt(Math.abs(x.remainingKm))} km`:`Faltan ${fmt(x.remainingKm)} km`}<small>${x.nextDueMileage!=null?`Próximo ${fmt(x.nextDueMileage)} km`:''}</small></span></button>`).join(''):'<p class="muted cc-empty">No hay servicios próximos ni vencidos.</p>'}</div></article>
  <article class="cc-panel cc-search-panel"><div class="cc-panel-head"><h2>Buscar vehículo</h2></div><div class="cc-searchbox">${uiIcon('search')}<input id="ccVehicleSearch" placeholder="Buscar por placa o número interno" aria-label="Buscar por placa o número interno" autocomplete="off"></div><h3>Vehículos</h3><div id="ccVehicleResults" class="cc-vehicle-results">${vehicles.slice(0,4).map(v=>ccVehicleResult(v)).join('')}</div><button id="goVehicles" class="textbtn cc-all-link">Ir a la lista de vehículos →</button></article>
 </section>
 <section class="cc-bottom">
  <article class="cc-panel cc-status-panel"><div class="cc-panel-head"><h2>Estado De Servicios</h2></div><div class="cc-status-content"><div class="cc-donut" style="background:conic-gradient(#22a447 0 ${pct('UP_TO_DATE')}%,#f5ad22 ${pct('UP_TO_DATE')}% ${pct('UP_TO_DATE')+pct('DUE_SOON')}%,#e52f35 ${pct('UP_TO_DATE')+pct('DUE_SOON')}% ${pct('UP_TO_DATE')+pct('DUE_SOON')+pct('OVERDUE')}%,#98a2b3 0)"><div><small>Total servicios</small><strong>${totalServices}</strong></div></div><div class="cc-legend"><span><i class="green-dot"></i>Al día <b>${serviceCounts.UP_TO_DATE}</b></span><span><i class="orange-dot"></i>Próximo <b>${serviceCounts.DUE_SOON}</b></span><span><i class="red-dot"></i>Vencido <b>${serviceCounts.OVERDUE}</b></span><span><i class="gray-dot"></i>Sin historial <b>${serviceCounts.NO_BASELINE}</b></span></div><div class="cc-common"><h3>Servicios más comunes</h3>${common.map(x=>`<div><span>${esc(x[0])}</span><b>${x[1]}</b></div>`).join('')}</div></div></article>
  <article class="cc-panel cc-actions"><div class="cc-panel-head"><h2>Acciones rápidas</h2></div><div class="cc-action-grid"><button data-go="vehicles">${uiIcon('vehicle')}<span>Vehículos</span></button><button data-go="plans">${uiIcon('service')}<span>Planes</span></button><button data-go="reports">${uiIcon('reports')}<span>Reportes</span></button><button data-go="users">${uiIcon('users')}<span>Usuarios</span></button></div></article>
 </section>
 <section id="ccDetail" class="cc-detail" hidden></section>`;
 const renderStatus=status=>{const filtered=rows.filter(x=>x.status===status),labels={OVERDUE:'Vencidos',DUE_SOON:'Próximos'};const box=document.getElementById('ccDetail');box.hidden=false;box.innerHTML=card(`<div class="sectionhead"><div><h2>${labels[status]}</h2><p class="muted">${filtered.length} servicio${filtered.length===1?'':'s'} en este estado.</p></div><button id="closeCcDetail" class="secondary">Cerrar</button></div>${filtered.length?`<div class="prioritytable">${filtered.map(x=>`<div class="priorityrow"><span><b>${esc(x.plate)}</b><small>${x.internalNumber?`Interno ${esc(x.internalNumber)}`:''}</small></span><span><b class="service-name-icon">${serviceNameWithIcon(x.serviceName)}</b></span><span>${statusBadge(x.status)}</span><span>${x.remainingKm==null?'—':x.remainingKm<0?`${fmt(Math.abs(x.remainingKm))} km vencido`:`Faltan ${fmt(x.remainingKm)} km`}</span><span><button class="dashmaint" data-vehicle="${x.vehicleId}">Ver</button></span></div>`).join('')}</div>`:''}`);document.getElementById('closeCcDetail').onclick=()=>box.hidden=true;box.querySelectorAll('.dashmaint').forEach(b=>b.onclick=()=>maintenanceView(b.dataset.vehicle));box.scrollIntoView({behavior:'smooth',block:'start'})};
 const renderStaleMileage=()=>{const box=document.getElementById('ccDetail');box.hidden=false;box.innerHTML=card(`<div class="sectionhead"><div><h2>Vehículos sin kilometraje actualizado</h2><p class="muted">${staleMileage.length} vehículo${staleMileage.length===1?'':'s'} con más de 1 día desde la última lectura.</p></div><button id="closeCcDetail" class="secondary">Cerrar</button></div>${staleMileage.length?`<div class="stale-mileage-list">${staleMileage.map(v=>{const days=Math.floor((Date.now()-new Date(v.mileageUpdatedAt).getTime())/86400000);return `<button class="stale-mileage-row cc-vehicle-result" data-vehicle="${v.id}"><span><small>${v.internalNumber?`Interno ${esc(v.internalNumber)}`:''}</small><b>${esc(v.plate)}</b><em>${esc(v.brand)} ${esc(v.model)}</em></span><span><strong>${fmt(v.currentMileage)} km</strong><small>Última lectura: ${new Date(v.mileageUpdatedAt).toLocaleString('es-CO')}</small><em>${days} día${days===1?'':'s'} sin actualizar</em></span></button>`}).join('')}</div>`:'<div class="report-empty"><b>Todo al día</b><small>Todos los vehículos tienen una lectura de kilometraje de las últimas 24 horas.</small></div>'}`);document.getElementById('closeCcDetail').onclick=()=>box.hidden=true;wireCcVehicles();box.scrollIntoView({behavior:'smooth',block:'start'})};
 document.querySelectorAll('.cc-kpi.clickable[data-status]').forEach(k=>k.onclick=()=>renderStatus(k.dataset.status));document.getElementById('staleMileageCard').onclick=renderStaleMileage;document.getElementById('showAllDue').onclick=()=>renderStatus(d.overdue?'OVERDUE':'DUE_SOON');
 document.querySelectorAll('.dashmaint').forEach(b=>b.onclick=()=>maintenanceView(b.dataset.vehicle));document.getElementById('refreshdash').onclick=()=>renderDashboard(vehicles);document.getElementById('goVehicles').onclick=()=>adminShell('vehicles');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>adminShell(b.dataset.go));
 const input=document.getElementById('ccVehicleSearch'),results=document.getElementById('ccVehicleResults');input.oninput=()=>{const q=input.value.trim().toUpperCase(),found=!q?vehicles.slice(0,4):vehicles.filter(v=>String(v.plate||'').toUpperCase().includes(q)||String(v.internalNumber||'').toUpperCase().includes(q)).slice(0,6);results.innerHTML=found.length?found.map(v=>ccVehicleResult(v)).join(''):'<p class="muted cc-empty">No se encontró ningún vehículo.</p>';wireCcVehicles()};
 wireCcVehicles()
}
function ccVehicleResult(v){return `<button class="cc-vehicle-result" data-vehicle="${v.id}"><span><small>${v.internalNumber?`Interno ${esc(v.internalNumber)}`:''}</small><b>${esc(v.plate)}</b><em>${esc(v.brand)} ${esc(v.model)}</em></span><strong>${fmt(v.currentMileage)} km</strong></button>`}
function wireCcVehicles(){document.querySelectorAll('.cc-vehicle-result').forEach(b=>b.onclick=()=>maintenanceView(b.dataset.vehicle))}
