async function renderNotifications(){
 const main=document.getElementById('main');main.innerHTML=card(`${moduleTitle('alert','Notificaciones','Controla cómo AutoControl QR te avisa sobre mantenimientos próximos y vencidos.')}<p class="muted">Cargando…</p>`);
 const [cr,nr,hr]=await Promise.all([req(api+'/company'),req(api+'/notifications'),req(api+'/notifications/history')]);
 if(!cr.r?.ok||!nr.r?.ok){main.innerHTML=card(`${moduleTitle('alert','Notificaciones','Alertas de mantenimiento.')}<p class="error">No se pudo cargar la configuración.</p>`);return}
 const c=cr.j.data,items=nr.j.data||[],history=hr.r?.ok?(hr.j.data||[]):[];
 const active=items.filter(x=>(x.status==='OVERDUE'&&c.notificationOverdue)||(x.status==='DUE_SOON'&&c.notificationDueSoon));
 main.innerHTML=`<div class="notification-head">${moduleTitle('alert','Notificaciones','Alertas de mantenimiento próximas y vencidas.')}</div>
 ${card(`<div class="notification-settings-head"><div><h2>Configuración</h2><p class="muted">El administrador decide qué alertas utilizar y con qué frecuencia.</p></div><label class="switchline"><input id="notifyEnabled" type="checkbox" ${c.notificationEnabled?'checked':''}> Activar notificaciones</label></div>
 <form id="notificationSettings" class="notification-settings-grid">
  <label><span>Alertas internas</span><select name="internal"><option value="true" ${c.notificationInternal?'selected':''}>Activadas</option><option value="false" ${!c.notificationInternal?'selected':''}>Desactivadas</option></select></label>
  <label><span>Correo electrónico</span><select name="emailEnabled"><option value="false" ${!c.notificationEmailEnabled?'selected':''}>Desactivado</option><option value="true" ${c.notificationEmailEnabled?'selected':''}>Preparar correo</option></select></label>
  <label><span>Correo destinatario</span><input name="email" type="email" value="${esc(c.notificationEmail||c.email||'')}" placeholder="mantenimiento@empresa.com"></label>
  <label><span>Recordar vencidos cada</span><select name="repeatDays">${[3,7,15,30].map(x=>`<option value="${x}" ${c.notificationRepeatDays===x?'selected':''}>${x} días</option>`).join('')}</select></label>
  <label class="checkline"><input name="dueSoon" type="checkbox" ${c.notificationDueSoon?'checked':''}> Avisar cuando esté Próximo</label>
  <label class="checkline"><input name="overdue" type="checkbox" ${c.notificationOverdue?'checked':''}> Avisar cuando esté Vencido</label>
  <div class="notification-save"><button>Guardar configuración</button><span id="notifyMsg"></span></div>
 </form>`,'notification-settings-card')}
 <section class="notification-grid">
  ${card(`<div class="sectionhead"><div><h2>Alertas actuales</h2><p class="muted">${active.length} servicio${active.length===1?'':'s'} requiere${active.length===1?'':'n'} atención.</p></div></div><div class="notification-list">${active.length?active.map(x=>`<div class="notification-row"><span class="notification-service-icon">${serviceIcon(x.serviceName)}</span><span><small>${x.internalNumber?`Interno ${esc(x.internalNumber)}`:''}</small><b>${esc(x.plate)}</b><em>${esc(x.serviceName)}</em></span><span>${statusBadge(x.status)}<small>${x.nextDueMileage!=null?`Programado: ${fmt(x.nextDueMileage)} km`:''}</small></span><button class="secondary notifyRecord" data-v="${x.vehicleId}" data-s="${x.serviceId}" data-st="${x.status}">Marcar avisado</button></div>`).join(''):'<div class="report-empty"><b>Sin alertas pendientes</b><small>No hay servicios próximos o vencidos según la configuración actual.</small></div>'}</div>`)}
  ${card(`<div class="sectionhead"><div><h2>Historial</h2><p class="muted">Últimos avisos registrados.</p></div></div><div class="notification-history">${history.length?history.slice(0,20).map(x=>`<div><span><b>${esc(x.plate)}</b><small>${esc(x.serviceName)}</small></span><span>${statusBadge(x.status)}</span><span><b>${x.channel==='EMAIL'?'Correo':'Interna'}</b><small>${new Date(x.createdAt).toLocaleString('es-CO')}</small></span></div>`).join(''):'<p class="muted cc-empty">Todavía no hay avisos registrados.</p>'}</div>`)}
 </section>
 <div class="notification-note"><b>Correo automático:</b> la configuración queda preparada en esta versión. Para enviar correos reales necesitaremos conectar un proveedor de correo transaccional. WhatsApp queda reservado como siguiente canal.</div>`;
 document.getElementById('notificationSettings').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),payload={enabled:document.getElementById('notifyEnabled').checked,internal:f.get('internal')==='true',emailEnabled:f.get('emailEnabled')==='true',email:String(f.get('email')||''),dueSoon:f.get('dueSoon')==='on',overdue:f.get('overdue')==='on',repeatDays:Number(f.get('repeatDays'))};const r=await req(api+'/company/notifications',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const m=document.getElementById('notifyMsg');m.className=r.r?.ok?'success':'error';m.textContent=r.r?.ok?'Configuración guardada.':'No se pudo guardar.'};
 document.querySelectorAll('.notifyRecord').forEach(b=>b.onclick=async()=>{const r=await req(api+'/notifications/mark-sent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId:b.dataset.v,serviceId:b.dataset.s,status:b.dataset.st,channel:'INTERNAL',recipient:null})});if(r.r?.ok)renderNotifications()})
}
