async function renderUsers(){
 const main=document.getElementById('main'),out=await req(api+'/users');
 if(!out.r||!out.r.ok){main.innerHTML=card('<p class="error">No se pudieron cargar los usuarios.</p>');return}
 const users=out.j.data||[];
 const userCard=u=>`<article class="user-card"><div class="user-identity"><div class="user-avatar">${esc((u.fullName||'?').trim().charAt(0).toUpperCase())}</div><div><strong>${esc(u.fullName)}</strong><small>${esc(u.email)}</small><div class="user-tags"><span class="rolepill">${u.role==='COMPANY_ADMIN'?'Administrador':'Técnico'}</span><span class="badge ${u.status==='ACTIVE'?'good':'mutedb'}">${u.status==='ACTIVE'?'Activo':'Inactivo'}</span></div></div></div><div class="user-actions"><button class="secondary edituser" data-id="${u.id}">Editar</button><button class="secondary userpassword" data-id="${u.id}">Contraseña</button><button class="textbtn ${u.status==='ACTIVE'?'dangertext':''} userstatus" data-id="${u.id}" data-status="${u.status==='ACTIVE'?'INACTIVE':'ACTIVE'}">${u.status==='ACTIVE'?'Desactivar':'Activar'}</button></div></article>`;
 main.innerHTML=card(`<div class="top user-page-head">${moduleTitle('users','Usuarios','Administra quién puede entrar a AutoControl QR y qué función cumple.')}</div><div class="user-create-title"><h2>Nuevo usuario</h2><p class="muted">Los técnicos trabajan únicamente sobre el vehículo que seleccionan o escanean. Los administradores gestionan la empresa.</p></div><form id="createuser" class="user-create-grid"><label>Nombre completo<input name="name" placeholder="Nombre y apellido" required></label><label>Correo<input name="email" type="email" placeholder="usuario@empresa.com" required></label><label>Contraseña<input name="password" type="password" minlength="8" placeholder="Mínimo 8 caracteres" required></label><label>Rol<select name="role"><option value="TECHNICIAN">Técnico</option><option value="COMPANY_ADMIN">Administrador</option></select></label><div class="user-create-action"><button>Crear usuario</button></div></form><p id="usererr" class="error"></p>`)+`<div class="user-list-head"><h2><span id="userCount">${users.length}</span> usuario${users.length===1?'':'s'}</h2><div class="user-search"><input id="userSearch" type="search" placeholder="Buscar por nombre o correo" aria-label="Buscar por nombre o correo" autocomplete="off"></div></div><div id="userList" class="user-list">${users.length?users.map(userCard).join(''):'<div class="no-search-results">Todavía no hay usuarios.</div>'}</div>`;
 document.getElementById('createuser').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const x=await req(api+'/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:f.get('name'),email:f.get('email'),password:f.get('password'),role:f.get('role')})});if(!x.r||!x.r.ok){document.getElementById('usererr').textContent=x.j.error?.message||'No se pudo crear el usuario.';return}renderUsers()};
 const wire=()=>{
  document.querySelectorAll('.edituser').forEach(b=>b.onclick=()=>editUserModal(users.find(x=>x.id===b.dataset.id)));
  document.querySelectorAll('.userpassword').forEach(b=>b.onclick=()=>passwordUserModal(users.find(x=>x.id===b.dataset.id)));
  document.querySelectorAll('.userstatus').forEach(b=>b.onclick=async()=>{const u=users.find(x=>x.id===b.dataset.id),verb=b.dataset.status==='INACTIVE'?'desactivar':'activar';if(!confirm(`¿${verb.charAt(0).toUpperCase()+verb.slice(1)} a ${u?.fullName||'este usuario'}?`))return;const x=await req(`${api}/users/${b.dataset.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:b.dataset.status})});if(!x.r||!x.r.ok)return alert(x.j.error?.message||'No se pudo cambiar el estado.');renderUsers()});
 };wire();
 document.getElementById('userSearch').oninput=e=>{const q=e.target.value.trim().toLocaleLowerCase('es'),filtered=!q?users:users.filter(u=>[u.fullName,u.email].some(x=>String(x||'').toLocaleLowerCase('es').includes(q)));document.getElementById('userCount').textContent=filtered.length;document.getElementById('userList').innerHTML=filtered.length?filtered.map(userCard).join(''):'<div class="no-search-results">No encontramos usuarios con ese criterio.</div>';wire()};
}
function editUserModal(u){
 if(!u)return;
 openFormModal({title:`Editar usuario · ${u.fullName}`,body:`<label>Nombre completo<input name="name" value="${esc(u.fullName)}" required></label><label>Correo<input name="email" type="email" value="${esc(u.email)}" required></label><label>Rol<select name="role"><option value="TECHNICIAN" ${u.role==='TECHNICIAN'?'selected':''}>Técnico</option><option value="COMPANY_ADMIN" ${u.role==='COMPANY_ADMIN'?'selected':''}>Administrador</option></select></label>`,onSubmit:async(f,err)=>{const x=await req(`${api}/users/${u.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fullName:f.get('name'),email:f.get('email'),role:f.get('role')})});if(!x.r||!x.r.ok){err.textContent=x.j.error?.message||'No se pudo editar el usuario.';return false}renderUsers();return true}})
}
function passwordUserModal(u){
 if(!u)return;
 openFormModal({title:`Cambiar contraseña · ${u.fullName}`,body:`<label>Nueva contraseña<input name="password" type="password" minlength="8" placeholder="Mínimo 8 caracteres" required></label><label>Confirmar contraseña<input name="confirm" type="password" minlength="8" placeholder="Repite la contraseña" required></label>`,onSubmit:async(f,err)=>{const password=String(f.get('password')||''),confirmPassword=String(f.get('confirm')||'');if(password.length<8){err.textContent='La contraseña debe tener mínimo 8 caracteres.';return false}if(password!==confirmPassword){err.textContent='Las contraseñas no coinciden.';return false}const x=await req(`${api}/users/${u.id}/password`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!x.r||!x.r.ok){err.textContent=x.j.error?.message||'No se pudo cambiar la contraseña.';return false}return true}})
}
